version: '3.0'
services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb_debian # TODO: change to mariadb
    container_name: mariadb_debian # TODO: change to mariadb
    restart: always
    ports:
      - "3000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # volumes:
    #   - ./db_data:/var/lib/mysql
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx_debian # TODO: change to nginx
    container_name: nginx_debian # TODO: change to nginx
    restart: always
    ports:
      - "3002:443"
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/nginx/tools:/var/www/html